const shippingCompanies = [
  { code: "PIL", name: "Pacific International Lines" },
  { code: "GSL", name: "Layar Sentosa Shipping" },
  { code: "HLC", name: "Hapag Lloyd" },
  { code: "IAL", name: "Interasia Lines" },
  { code: "MSC", name: "Mediterranean Shipping Company" },
  { code: "OOL", name: "Orient Overseas Container Line" },
  { code: "SIT", name: "SITC Container Lines Co., Ltd" },
  { code: "SKR", name: "Sinokor Merchant Marine" },
  { code: "SSL", name: "Samudera" },
  { code: "WHL", name: "Wan Hai Lines" },
  { code: "YML", name: "Yang Ming Line" },
  { code: "EVG", name: "Evergreen Marine Indonesia" },
  { code: "LSSC", name: "Layar Sentosa Shipping" },
  { code: "ECON", name: "ECON SHIPPING" },
  { code: "OSL", name: "OCEANIC STAR LINE LTD" },
  { code: "PAL", name: "PAN ASIA LINE" },
  { code: "QAS", name: "QUANZHOU ANSHENG SHIPPING CO.,LTD" },
  { code: "TS", name: "T S LINES LTD" },
  { code: "TA", name: "TA ASIA LOGISTICS PTE., LTD" },
  { code: "TI", name: "TRANSINSULAR. PT" },
  { code: "UAFL", name: "UNITED AFRICA FEEDER LINES" },
  { code: "UNO", name: "UNO SHIPPING" },
  { code: "ASL", name: "ASEAN SEAS LINE CO., LTD" },
  { code: "RCL", name: "PT Bhum Mulia Prima" },
  { code: "KMD", name: "Korea Marine Transport" },
  { code: "KMTC", name: "Korea Marine Transport" },
  { code: "TMS", name: "Tresna Muda" },
  { code: "CMA", name: "CMA - CGM" },
  { code: "CNC", name: "CMA - CNC" },
  { code: "ANL", name: "CMA - ANL" },
  { code: "APL", name: "CMA - APL" },
  { code: "SWI", name: "SWIRE - THE CHINA NAVIGATION COMPANY PTE LTD" },
  { code: "FES", name: "FESCO LINES" },
  { code: "TSL", name: "T S LINES LTD" },
  { code: "UAF", name: "UNITED AFRICA FEEDER LINES" },
  { code: "KMC", name: "Korea Marine Transport" },
  { code: "SUD", name: "Ben Line" },
  { code: "HSA", name: "Ben Line" },
  { code: "HSD", name: "Ben Line" },
  { code: "COS", name: "COSCO Shipping Lines Indonesia" },
  { code: "ADM", name: "Admiral Lines" },
  { code: "NYK", name: "Nippon Yusen Kaisha Line (NYK Line Indonesia)" },
  { code: "MEAU", name: "Maerks Line (Pelayaran Bintang Putih)" },
  { code: "MOL", name: "MOL Indonesia" },
];

export default shippingCompanies;
